name: Compile Native Bindings

on: workflow_dispatch

jobs:
  compile-linux-x64:
    runs-on: ubuntu-latest
    env: 
      COMMIT_MESSAGE: Automated Linux-x64 Build Files
      COMMIT_AUTHOR: Continuous Integration
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.OTTERKIT_GITHUB_TOKEN }}
    
    - name: Compile Native Bindings
      run: |
        cd Libraries/Otterkit.Native/nativelib

        clang -shared -Wl,-rpath -fPIC -O3 -Wall -W -o ../build/nativelib.so allocator.c u8console.c decimals.c ../decNumber/decContext.c ../decNumber/decDouble.c ../decNumber/decQuad.c ../decNumber/decNumber.c ../decNumber/decimal128.c ../decNumber/decimal64.c
        
    - name: GIT Commit Build Files
      run: |
        git config --global user.name "${{ env.COMMIT_AUTHOR }}"
        git config --global user.email "KTSnowy@users.noreply.github.com"
        git pull
        git add --all
        git commit -m "${{ env.COMMIT_MESSAGE }}"
        git push

  compile-macos-x64:
    runs-on: macos-latest
    env: 
      COMMIT_MESSAGE: Automated macOS-x64 Build Files
      COMMIT_AUTHOR: Continuous Integration
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.OTTERKIT_GITHUB_TOKEN }}
    
    - name: Compile Native Bindings
      run: |
        cd Libraries/Otterkit.Native/nativelib

        clang -dynamiclib -O3 -Wall -W -o ../build/nativelib.dylib allocator.c u8console.c decimals.c ../decNumber/decContext.c ../decNumber/decDouble.c ../decNumber/decQuad.c ../decNumber/decNumber.c ../decNumber/decimal128.c ../decNumber/decimal64.c
        
    - name: GIT Commit Build Files
      run: |
        git config --global user.name "${{ env.COMMIT_AUTHOR }}"
        git config --global user.email "KTSnowy@users.noreply.github.com"
        git pull
        git add --all
        git commit -m "${{ env.COMMIT_MESSAGE }}"
        git push
  
  compile-windows-x64:
    runs-on: windows-latest
    env: 
      COMMIT_MESSAGE: Automated Windows-x64 Build Files
      COMMIT_AUTHOR: Continuous Integration
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.OTTERKIT_GITHUB_TOKEN }}
    
    - name: Compile Native Bindings
      shell: cmd
      run: |
        cd Libraries\Otterkit.Native\nativelib
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        
        cl.exe /O2 /LD /Fe:..\build\nativelib.dll allocator.c u8console.c decimals.c  ..\decNumber\decContext.c ..\decNumber\decDouble.c ..\decNumber\decQuad.c ..\decNumber\decNumber.c ..\decNumber\decimal128.c ..\decNumber\decimal64.c
        
    - name: GIT Commit Build Files
      run: |
        git config --global user.name "${{ env.COMMIT_AUTHOR }}"
        git config --global user.email "KTSnowy@users.noreply.github.com"
        git add --all
        git commit -m "${{ env.COMMIT_MESSAGE }}"
        git push
